#!/usr/bin/env bash

# change to directory script executes in
cd "$(dirname "$0")"

FILES=aliases,bash_profile,bash_prompt,bashrc,curlrc,editorconfig,exports,gitattributes,\
gitignore,gvimrc,hushlogin,inputrc,osx,paths,vimrc,wgetrc,zshrc,vim_encrypted_rc,eslintrc,\
tmux.conf

CWD=$(pwd)

# create a symlink for each of the files listed above
IFS=','
for FILE in $FILES; do
    if [ -r ".$FILE" ] && [ -f ".$FILE" ]
    then
        if [ -a "$HOME/.$FILE" ]
        then
            rm "$HOME/.$FILE"
        fi
        ln -s "$CWD/.$FILE" "$HOME/.$FILE"
        echo "$HOME/.$FILE linked to $CWD/.$FILE"
    fi
done;

# create ~/.vim if it doesn't exist
if [ ! -d "$HOME/.vim" ]
then
    mkdir "$HOME/.vim"
fi

# create a symlink at ~/.vim/snippets
ln -s "$CWD/snippets" "$HOME/.vim/snippets"
